<?php
/**
 * @var \Magento\Sales\Block\Order\Email\Items $block
 */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <!-- GST Headers -->
                <th class="item-gst-cgst" style="text-align: center;">
                    <?= $block->escapeHtml(__('CGST')) ?><br/>
                    <small><?= $block->escapeHtml(__('Rate Amount')) ?></small>
                </th>
                <th class="item-gst-sgst" style="text-align: center;">
                    <?= $block->escapeHtml(__('SGST')) ?><br/>
                    <small><?= $block->escapeHtml(__('Rate Amount')) ?></small>
                </th>
                <th class="item-gst-igst" style="text-align: center;">
                    <?= $block->escapeHtml(__('IGST')) ?><br/>
                    <small><?= $block->escapeHtml(__('Rate Amount')) ?></small>
                </th>
                
                <th class="item-qty">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-price">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getParentItem()): ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
