<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Sales\Block\Adminhtml\Order\Totals $block */
?>
<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer') ?>

    <?php if ($_totals): ?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else: ?>

                    <?php if ($_code == 'grand_total'): ?>
                        <?php
                        // Rounding Logic
                        $source = $block->getSource(); // Invoice or Order
                        $calculatedTotal = $_total->getValue();

                        $targetTotal = round($calculatedTotal);
                        $roundOff = round($targetTotal - $calculatedTotal, 2);

                        // Adjust Grand Total Value to displayed value
                        $_total->setValue($targetTotal);
                        $_total->setBaseValue($targetTotal);
                        ?>
                        <?php if (abs($roundOff) >= 0.01): ?>
                            <tr>
                                <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                                    <strong><?= $block->escapeHtml(__('Round Off')) ?></strong>
                                </td>
                                <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                                    <strong><?= /* @noEscape */ $source->formatPrice($roundOff) ?></strong>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endif; ?>

                    <tr class="col-<?= $block->escapeHtmlAttr($_code) ?>">
                        <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                            <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                        </td>
                        <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                            <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tfoot>
    <?php endif; ?>

    <?php $_totals = $block->getTotals('') ?>
    <?php if ($_totals): ?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else: ?>
                    <tr class="col-<?= $block->escapeHtmlAttr($_code) ?>">
                        <td <?= /* @noEscape */ $block->getLabelProperties() ?> class="label">
                            <?php if ($_total->getStrong()): ?>
                                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else: ?>
                                <?= $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif ?>
                        </td>

                        <?php if ($_total->getStrong()): ?>
                            <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else: ?>
                            <td <?= /* @noEscape */ $block->getValueProperties() ?>>
                                <span><?= /* @noEscape */ $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
<div style="font-size: 10px; font-style: italic; text-align: right; color: #303030; padding-top: 5px;">
    <?= $block->escapeHtml(__('* Rounding off is applicable as per Section 170 of CGST Act, 2017.')) ?>
</div>