<?php
/**
 * Copied from Magento_Sales::order/items.phtml to inject GST columns
 *
 * @var \Magento\Sales\Block\Order\Items $block
 */
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= $block->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="7" data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                
                <!-- GST Headers -->
                <th class="col cgst"><?= $block->escapeHtml(__('CGST')) ?></th>
                <th class="col sgst"><?= $block->escapeHtml(__('SGST')) ?></th>
                <th class="col igst"><?= $block->escapeHtml(__('IGST')) ?></th>
                
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
        </thead>
        <?php $items = $block->getItems(); ?>
        <?php foreach ($items as $item) :
            if ($item->getParentItem()) :
                continue;
            endif;
            ?>
            <tbody>
                <?= $block->getItemHtml($item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="7" data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
</div>
